version: '3.1'

services:
  db:
    container_name: db-workshop
    image: mariadb:10.6.4
    restart: unless-stopped
    environment:
      TZ: Europe/Madrid
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: bookshop
    ports:
      - 3306:3306
    volumes:
      - ../database/data/mariadb:/var/lib/mysql
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
